"""create memory schema

Revision ID: 55d0f1042d65
Revises: 
Create Date: 2026-08-23 16:20:01.548884
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55d0f1042d65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'model_id', 'content_hash', name='uq_embedding_entity_model_content')
    )
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embeddings_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_embeddings_entity_type'), ['entity_type'], unique=False)

    op.create_table('principals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_principals_external_id'), ['external_id'], unique=True)

    op.create_table('skills',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'channel', 'external_id', name='uq_conversation_identity')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_principal_id'), ['principal_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_message_ids', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_principal_id'), ['principal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_state'), ['state'], unique=False)

    op.create_table('conversation_summaries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('start_turn_sequence', sa.Integer(), nullable=False),
    sa.Column('end_turn_sequence', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'start_turn_sequence', 'end_turn_sequence', name='uq_summary_turn_range')
    )
    with op.batch_alter_table('conversation_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_summaries_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_turn_conversation_sequence')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turn_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'sequence', name='uq_message_turn_sequence')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_turn_id'), ['turn_id'], unique=False)

    # ### end Alembic commands ###
    op.execute(
        "CREATE VIRTUAL TABLE memories_fts USING fts5("
        "entity_id UNINDEXED, principal_id UNINDEXED, kind, canonical_key, value)"
    )
    op.execute(
        "CREATE VIRTUAL TABLE summaries_fts USING fts5("
        "entity_id UNINDEXED, conversation_id UNINDEXED, body)"
    )
    op.execute(
        "CREATE VIRTUAL TABLE skills_fts USING fts5("
        "entity_id UNINDEXED, name, description, body, triggers)"
    )
    op.execute(
        "CREATE VIRTUAL TABLE messages_fts USING fts5("
        "entity_id UNINDEXED, turn_id UNINDEXED, role, content)"
    )
    bind = op.get_bind()
    try:
        bind.exec_driver_sql("SELECT vec_version()")
    except Exception:
        pass
    else:
        bind.exec_driver_sql(
            "CREATE VIRTUAL TABLE memory_vectors USING vec0("
            "embedding float[768])"
        )


def downgrade() -> None:
    bind = op.get_bind()
    bind.exec_driver_sql("DROP TABLE IF EXISTS memory_vectors")
    bind.exec_driver_sql("DROP TABLE IF EXISTS messages_fts")
    bind.exec_driver_sql("DROP TABLE IF EXISTS skills_fts")
    bind.exec_driver_sql("DROP TABLE IF EXISTS summaries_fts")
    bind.exec_driver_sql("DROP TABLE IF EXISTS memories_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_turn_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_conversation_id'))

    op.drop_table('turns')
    with op.batch_alter_table('conversation_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_summaries_conversation_id'))

    op.drop_table('conversation_summaries')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_state'))
        batch_op.drop_index(batch_op.f('ix_memories_principal_id'))
        batch_op.drop_index(batch_op.f('ix_memories_kind'))

    op.drop_table('memories')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_principal_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_name'))
        batch_op.drop_index(batch_op.f('ix_skills_content_hash'))

    op.drop_table('skills')
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_principals_external_id'))

    op.drop_table('principals')
    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embeddings_entity_type'))
        batch_op.drop_index(batch_op.f('ix_embeddings_entity_id'))

    op.drop_table('embeddings')
    # ### end Alembic commands ###
